const employees = [
  {
    id: 2,
    name: "Amit",
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        title: "Fix login bug",
        description: "Resolve the login issue on the user dashboard.",
        date: "2025-04-21",
        category: "Bug Fix",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Update user profile UI",
        description: "Redesign the user profile page with new layout.",
        date: "2025-04-20",
        category: "UI/UX",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Write API documentation",
        description: "Document all user-related APIs in Notion.",
        date: "2025-04-19",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
    taskCount: {
      failed: 0,
      completed: 1,
      active: 2,
      newTask: 1,
    },
  },
  {
    id: 3,
    name: "Bhavana",
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        title: "Integrate payment gateway",
        description: "Add Stripe payment integration to the checkout page.",
        date: "2025-04-18",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Integrate payment gateway",
        description: "Add Stripe payment integration to the checkout page.",
        date: "2025-04-18",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Integrate payment gateway",
        description: "Add Stripe payment integration to the checkout page.",
        date: "2025-04-18",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Fix broken links",
        description: "Resolve 404 errors across the site.",
        date: "2025-04-17",
        category: "Bug Fix",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Write test cases",
        description: "Add unit tests for cart functionalities.",
        date: "2025-04-16",
        category: "Testing",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Design error page",
        description: "Create a custom 404 page design.",
        date: "2025-04-15",
        category: "Design",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
    taskCount: {
      failed: 1,
      completed: 2,
      active: 1,
      newTask: 1,
    },
  },
  {
    id: 4,
    name: "Chetan",
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        title: "Optimize database queries",
        description: "Improve performance of report generation queries.",
        date: "2025-04-14",
        category: "Performance",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Refactor codebase",
        description: "Clean up and modularize authentication code.",
        date: "2025-04-13",
        category: "Refactor",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Update onboarding docs",
        description: "Revise the internal onboarding guide for new devs.",
        date: "2025-04-12",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
    taskCount: {
      failed: 1,
      completed: 1,
      active: 1,
      newTask: 0,
    },
  },
  {
    id: 5,
    name: "Divya",
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        title: "Implement dark mode",
        description: "Add dark mode toggle across the platform.",
        date: "2025-04-11",
        category: "Feature",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Fix email notification bug",
        description: "Resolve issue with duplicate email sends.",
        date: "2025-04-10",
        category: "Bug Fix",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Setup CI/CD pipeline",
        description: "Automate deployments with GitHub Actions.",
        date: "2025-04-09",
        category: "DevOps",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Create product demo video",
        description: "Record walkthrough of core product features.",
        date: "2025-04-08",
        category: "Marketing",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Audit user permissions",
        description: "Ensure role-based access controls are enforced.",
        date: "2025-04-07",
        category: "Security",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
    taskCount: {
      failed: 1,
      completed: 2,
      active: 2,
      newTask: 2,
    },
  },
  {
    id: 6,
    name: "Eshan",
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        title: "Redesign dashboard",
        description: "Modernize layout and update charts.",
        date: "2025-04-06",
        category: "UI/UX",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Fix session timeout issue",
        description: "Session ends too soon while user is active.",
        date: "2025-04-05",
        category: "Bug Fix",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Implement search filter",
        description: "Add category filter to the blog search.",
        date: "2025-04-04",
        category: "Feature",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
    taskCount: {
      failed: 1,
      completed: 1,
      active: 1,
      newTask: 0,
    },
  },
];

const admin = [
  {
    name: "mijanur",
    id: 1,
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employee = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));

  return { employee, admin };
};
